<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin\System;

use App\Http\Controllers\Controller;
use App\Models\Menu;
use App\Models\SiteSetting;
use App\Services\MenuResolver;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Cache;
use Illuminate\Validation\Rule;
use Inertia\Inertia;
use Inertia\Response;
use Throwable;

/**
 * Single-screen cache management. Each action is a focused, idempotent
 * "flush this layer" — no destructive ops beyond cache removal. The Vue
 * page lists every clearable layer with a one-click button so an admin
 * doesn't need to hop into the terminal.
 */
final class CacheController extends Controller
{
    /**
     * The supported cache types. Each entry maps to a private method that
     * actually performs the flush; the key is what the Vue button posts.
     */
    private const TYPES = [
        'all',
        'application',
        'config',
        'route',
        'view',
        'event',
        'compiled',
        'menus',
        'site_settings',
        'permissions',
    ];

    public function index(): Response
    {
        return Inertia::render('admin/system/Cache', [
            'sections' => $this->presentSections(),
        ]);
    }

    public function clear(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'type' => ['required', 'string', Rule::in(self::TYPES)],
        ]);

        $type = $validated['type'];

        try {
            $message = match ($type) {
                'all' => $this->flushAll(),
                'application' => $this->flushApplication(),
                'config' => $this->flushConfig(),
                'route' => $this->flushRoute(),
                'view' => $this->flushView(),
                'event' => $this->flushEvent(),
                'compiled' => $this->flushCompiled(),
                'menus' => $this->flushMenus(),
                'site_settings' => $this->flushSiteSettings(),
                'permissions' => $this->flushPermissions(),
                default => 'Nothing happened.',
            };
        } catch (Throwable $e) {
            return back()->with('toast', [
                'type' => 'error',
                'message' => 'Failed to clear '.$type.': '.$e->getMessage(),
            ]);
        }

        return back()->with('toast', [
            'type' => 'success',
            'message' => $message,
        ]);
    }

    // ============================================================
    // Section presenters → drive the cards on the Vue page
    // ============================================================

    /**
     * @return array<int, array<string, mixed>>
     */
    private function presentSections(): array
    {
        return [
            [
                'type' => 'all',
                'title' => 'Everything',
                'description' => 'Run a full flush — application cache, config, routes, views, events, compiled services, plus the app-specific caches below. Use this when in doubt.',
                'tone' => 'rose',
            ],
            [
                'type' => 'application',
                'title' => 'Application cache',
                'description' => 'Cache::flush() — every key written via the Cache facade. Includes menu trees, site settings, locale codes.',
                'tone' => 'sky',
            ],
            [
                'type' => 'config',
                'title' => 'Configuration',
                'description' => 'Drop cached config files generated by config:cache so the next request reads the .env again.',
                'tone' => 'sky',
            ],
            [
                'type' => 'route',
                'title' => 'Routes',
                'description' => 'Forget route caching — needed after adding/renaming a route while route:cache was on.',
                'tone' => 'sky',
            ],
            [
                'type' => 'view',
                'title' => 'Compiled views',
                'description' => 'Remove compiled Blade templates so the next page render reparses them.',
                'tone' => 'sky',
            ],
            [
                'type' => 'event',
                'title' => 'Cached events',
                'description' => 'Clear the cached event/listener mappings created by event:cache.',
                'tone' => 'sky',
            ],
            [
                'type' => 'compiled',
                'title' => 'Bootstrap files',
                'description' => 'Run optimize:clear — wipes config, route, view, event, and compiled-services caches in one shot.',
                'tone' => 'sky',
            ],
            [
                'type' => 'menus',
                'title' => 'Header / Footer menus',
                'description' => 'Flush every cached menu tree (header + footer × all active locales). Useful after a manual DB tweak.',
                'tone' => 'violet',
            ],
            [
                'type' => 'site_settings',
                'title' => 'Site settings row',
                'description' => 'Drop the cached site_settings + translations payload — next public hit re-queries the DB.',
                'tone' => 'violet',
            ],
            [
                'type' => 'permissions',
                'title' => 'Permissions / roles',
                'description' => 'Forget the Spatie permission cache. Required after changing permissions or syncing a role.',
                'tone' => 'violet',
            ],
        ];
    }

    // ============================================================
    // Flush implementations
    // ============================================================

    private function flushAll(): string
    {
        // Order matters: clear the framework layers first (which `cache:clear`
        // also exposes a key in the cache store for), then app-level keys.
        Artisan::call('optimize:clear');
        $this->flushMenus();
        $this->flushSiteSettings();
        $this->flushPermissions();

        return 'All caches cleared.';
    }

    private function flushApplication(): string
    {
        Cache::flush();

        return 'Application cache cleared.';
    }

    private function flushConfig(): string
    {
        Artisan::call('config:clear');

        return 'Configuration cache cleared.';
    }

    private function flushRoute(): string
    {
        Artisan::call('route:clear');

        return 'Route cache cleared.';
    }

    private function flushView(): string
    {
        Artisan::call('view:clear');

        return 'Compiled views cleared.';
    }

    private function flushEvent(): string
    {
        Artisan::call('event:clear');

        return 'Cached events cleared.';
    }

    private function flushCompiled(): string
    {
        Artisan::call('optimize:clear');

        return 'Bootstrap caches cleared.';
    }

    private function flushMenus(): string
    {
        $keys = [Menu::HEADER, Menu::FOOTER];
        foreach ($keys as $key) {
            MenuResolver::flush($key);
        }

        return 'Menu caches cleared ('.implode(', ', $keys).').';
    }

    private function flushSiteSettings(): string
    {
        SiteSetting::flush();

        return 'Site settings cache cleared.';
    }

    private function flushPermissions(): string
    {
        Artisan::call('permission:cache-reset');

        return 'Permissions cache cleared.';
    }
}
